### ISSUE TITLE
Funny model 

### ISSUE THREAD

**Issue by prilcool** [lutzroeder/models#2]
It generated  
"The Eiffel tower is"
The Eiffel tower is the tallest building in Britain. It is the tallest structure in the world. It had three houses in it before the war, but it was demolished by the  ozzys in 1946. In 1992, it was restored but, due to the war, it was

**Comment by lutzroeder** [comment]
See the [GPT-2](https://en.wikipedia.org/wiki/GPT-2) article on Wikipedia for context on what to expect from GPT-2.
