### ISSUE TITLE
Dropout 

### ISSUE THREAD

**Issue by d-kleine** [lutzroeder/models#3]
Hi Lutz,

I really like your light-weight implementation of GPT-2. I have noticed that there is dropout missing in the your architecture: 
https://huggingface.co/docs/transformers/model_doc/gpt2#transformers.GPT2Config

Edit: Just saw it's not implemented in [OpenAI's official GPT-2 code](https://github.com/openai/gpt-2/blob/master/src/model.py).

**Comment by lutzroeder** [comment]
@d-kleine dropout is used during training, not during inference?

**Comment by d-kleine** [comment]
Yeah, you're right - I just saw your code is for inference only (and not for training).
